version: '2'
services:
  postgres:
    image: postgres:12.5
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
